services:
  - type: web
    name: price-tracker-backend
    env: python
    startCommand: gunicorn telegram_auth_backend:app
    envVars:
      - key: FIREBASE_CREDENTIALS
        value: FIREBASE_CREDENTIALS
      - key: TELEGRAM_BOT_TOKEN
        value: TELEGRAM_BOT_TOKEN
    autoDeploy: true

  - type: worker
    name: price-checker
    env: python
    startCommand: python price_checker.py
    envVars:
      - key: FIREBASE_CREDENTIALS
        value: FIREBASE_CREDENTIALS
      - key: TELEGRAM_BOT_TOKEN
        value: TELEGRAM_BOT_TOKEN
    autoDeploy: true
