services:
  - type: web
    name: price-tracker-backend
    env: python
    startCommand: gunicorn telegram_auth_backend:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN

  - type: worker
    name: price-checker
    env: python
    startCommand: python price_checker.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
